version: '3.4'

name: auth
services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    ports:
      - ${KEYCLOAK_PORT}:${KEYCLOAK_PORT}
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/:/opt/keycloak/data/import:ro
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm'
    restart: always

  nest:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    depends_on:
      - keycloak
    environment:
      NODE_ENV: development
      KEYCLOAK_BASE_URL: 'http://keycloak:8080'
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_REALM_RSA_PUBLIC_KEY: ${KEYCLOAK_REALM_RSA_PUBLIC_KEY}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_ADMIN_CLIENT_SECRET: ${KEYCLOAK_ADMIN_CLIENT_SECRET}

volumes:
  node_modules:
