version: '3.8'

name: auth
services:
  auth:
    container_name: cinepik-auth
    build: .
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    environment:
      NODE_ENV: development
    env_file:
      - .env
    networks:
      - cinepik-network
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:${LS_PORT}
        tag: cinepik-auth

networks:
  cinepik-network:
    name: cinepik-network
    external: true
