version: '3.8'

name: auth
services:
  auth:
    container_name: cinepik-auth
    build: .
    command: npm run start:dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    environment:
      NODE_ENV: development
    env_file:
      - .env
    networks:
      - cinepik-network

volumes:
  node_modules:


networks:
  cinepik-network:
    name: cinepik-network
    external: true
