apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinepik-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinepik-auth
  template:
    metadata:
      labels:
        app: cinepik-auth
    spec:
      containers:
        - image: sebam/cinepik-auth:latest
          name: cinepik-auth
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          env:
            - name: NODE_PORT
              value: '3000'
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: KEYCLOAK_CLIENT_SECRET
            - name: KEYCLOAK_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_BASE_URL
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_REALM
            - name: KEYCLOAK_REALM_RSA_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: KEYCLOAK_REALM_RSA_PUBLIC_KEY
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_CLIENT_ID
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: KEYCLOAK_ADMIN_PASSWORD
          ports:
            - containerPort: 3000